UniQueCorn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accounts_urls
from accounts.views import index
from home import urls as home_urls
from products import urls as products_urls
from cart import urls as cart_urls
from checkout import urls as checkout_urls
from issuetracker import urls as issuetracker_urls
from products.views import all_products
from django.views import static
from .settings import MEDIA_ROOT


urlpatterns = [
    url(r'^', include(home_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^index$', index, name="account_index"),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^products$', all_products, name="products"),
    url(r'^products/', include(products_urls)),
    url(r'^cart/', include(cart_urls)),
    url(r'^checkout/', include(checkout_urls)),
    url(r'^issues/', include(issuetracker_urls)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
]

cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name="view_cart"),
    url(r'^add/(?P<id>\d+$)', add_to_cart, name="add_to_cart"),
    url(r'^adjust/(?P<id>\d+$)', adjust_cart, name="adjust_cart"),
]

home/urls.py
from django.conf.urls import url
from .views import index, about, blog, uqc_app, contact

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^about/$', about, name="about"),
    url(r'^blog/$', blog, name="blog"),
    url(r'^uqc_app/$', uqc_app, name="uqc_app"),
    url(r'^contact/$', contact, name="contact_us")
]

issuetracker/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User


class Issue(models.Model):
    suggestion_choices = ((True, 'Feature'), (False, 'Bug Fix'))
    is_feature = models.BooleanField(blank=False, default=False, choices=suggestion_choices)
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField()
    posted_by = models.CharField(max_length=50)
    votes = models.IntegerField(default=0)
    comments_count = models.IntegerField(default=0)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Issues"


class IssueComment(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='comment')
    subject = models.CharField(max_length=100, blank=False)
    comment = models.TextField()
    posted_by = models.CharField(max_length=50)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=254, default='')
    description = models.TextField()
    coins = models.SmallIntegerField(blank=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.core.mail import send_mail
from django.contrib import messages

def index(request):
    """Display the home page."""
    return render(request, "index_home.html")

def about(request):
    """Display the about page."""
    return render(request, "about.html")

def blog(request):
    """Display the blog page."""
    return render(request, "blog.html")

def uqc_app(request):
    """Display the UniQue Corn App page."""
    return render(request, "uqc-app.html")

def contact(request):
    """Display the contact us page."""

    if request.method == 'POST':
        try:
            subject = request.POST.get('subject')
            name = request.POST.get('name')
            email = request.POST.get('email')
            message = request.POST.get('message')

            message_body = "Email sent by {} ({}) through the UniQueCorn website.\n\n{}".format(name, email, message)
            
        except Exception as e:
            messages.error(request, "Your email has failed.")
            return redirect(reverse('index'))

        send_mail(
            subject, 
            message_body,
            'websiteadmin@anthonybonello.co.uk',
            ['websiteadmin@anthonybonello.co.uk'],
            fail_silently=False
        )
        messages.success(request, "You have sent an email successfully.")
        return redirect(reverse('index'))

    return render(request, "contact.html")

home/templates/about.html
{% extends "base.html" %}

{% block page_title %}
UniQueCorn - Issue Tracker | About
{% endblock %}

{% block showcase %}
<div class="main-title">
    <div class="color-cover"></div>
    <div class="title">
        <h1>Unique Corn - Issue Tracker - ABOUT</h1>
    </div>
</div>
{% endblock showcase %}


{% block content %}
<p class="about-intro">The main app whose issues are tracked with this app is as real as the <span class="emphasise">Unicorns</span> that Theresa May is currently hunting. If you are curious about this and would like to read more, please go <a href="{% url 'uqc_app' %}" class="about-product-link">here</a>.</p>

<p class="about-intro">UniQue Corn app is mired in bugs and lack of proper functionality, so there will be lots to report. Users can also vote for features and bugs they would like to see fixed.</p>

<p class="about-subtitle">Background</p>
<p class="about-text">In a post-brexit dystopia, when people in the UK are hungry and food is scarce, the Prime Minister decides to turn to technology to solve her most pressing problem, feeding the people. This step was not without its roller coaster of issues. In a similar fashion to brexit itself, it turned out to be a cliff-edge jump without a parachute. People who depended on this app for sustainance started dying. Apparently, this magic food was no miracle at all and turned out to be as real as the Unicorns from whom the name derives.</p>

<p class="about-text">At least Jeremy Corbyn came to the rescue and decided to start a project with the intention to improve this unremarkable piece of technology. The aim was to track bugs and ask users to collaborate by suggesting any features they would like to be included in this app.</p>

<p class="about-text">Unfortunately for me, being a slave of the system, I was assigned the infamous task of developing this issue tracker.</p>

{% endblock %}

home/templates/blog.html
{% extends "base.html" %}

{% block page_title %}
UniQueCorn - Issue Tracker | Blog
{% endblock %}

{% block showcase %}
<div class="main-title">
    <div class="color-cover"></div>
    <div class="title">
        <h1>Unique Corn - Issue Tracker - Blog</h1>
    </div>
</div>
{% endblock showcase %}


{% block content %}

<p class="blog-date">21 May 2019</p>
<p class="blog-title">App first released</p>
<p class="blog-text">This miraculous app will feed the UK population. It is still undecided whether EU citizens living in the UK will be
allowed to use it at this stage. We can leave this decision till later after all so many decisions have been kicked back
in time during the brexit process, so why not this one too?</p>

<p class="blog-date">6 June 2019</p>
<p class="blog-title">First problems appear</p>
<p class="blog-text">Why should this perfect app ever have problems is beyond my understanding. Technology should be the solution of
everything including borders and food.</p>

<p class="blog-date">25 June 2019</p>
<p class="blog-title">Planning of an issue tracker</p>
<p class="blog-text">Jeremy Corbyn decided to finally get off the wall and start helping with this app. Now everyone knows exactly on which
side he is. Some people still think that he is motivated with helping people. I am not convinced and since I am writing
this blog I will say it the way I feel it.</p>

{% endblock %}

home/templates/contact.html
{% extends "base.html" %}

{% block page_title %}
UniQueCorn - Issue Tracker | Contact
{% endblock %}

{% block showcase %}
<div class="main-title">
    <div class="color-cover"></div>
    <div class="title">
        <h1>Unique Corn - Issue Tracker - Contact Us</h1>
    </div>
</div>
{% endblock showcase %}


{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="section-title text-center">
            <h2 class="contact-title">Contact Us</h2>
            <p class="contact-text">
                Use this form if you need to get in touch for reasons such as the following:
            </p>
            <ul class="contact-unordered-list">
                <li class="contact-list-item">You have problems with registering.</li>
                <li class="contact-list-item">You have problems with logging in.</li>
                <li class="contact-list-item">You noticed something wrong on this web site.</li>
                <li class="contact-list-item">You have a suggestion to improve this web site.</li>
                <li class="contact-list-item">You have problems buying and paying for coins.</li>
                <li class="contact-list-item">You have problems with creating a new feature or bug even though you have enough coins.</li>
                <li class="contact-list-item">You have problems adding a comment to a feature or bug.</li>
                <li class="contact-list-item">You have problems with voting up a feature or bug even though you have enough coins.</li>
            </ul>
            <p class="contact-text small">
                All fields are required.
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 contact-form-container">
        <form method="POST" id="contactForm" data-toggle="validator">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name" id="nameLabel">Name:</label>
                <input type="text" class="form-control" id="id_name" name="name" placeholder="Your Name here" required />
            </div>
            <div class="form-group">
                <label for="id_email" id="emailLabel">Email:</label>
                <input type="email" class="form-control" id="id_email" name="email" placeholder="example@example.com"
                    required />
            </div>
            <div class="form-group">
                <label for="id_subject" id="subjectLabel">Subject:</label>
                <input type="text" class="form-control" id="id_subject" name="subject" placeholder="Subject here" required />
            </div>
            <div class="form-group">
                <label for="id_message" id="is_messageLabel">Message:</label>
                <textarea class="form-control" name="message" id="id_message" cols="30" rows="10"
                    placeholder="please write your message here" required minlength="3"></textarea>
            </div>
            <div class="padding">
                <button type="submit" class="btn center-block section dusty" id="btn-submit">Submit</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

home/templates/index_home.html
{% extends "base.html" %}

{% block page_title %}
UniQueCorn - Issue Tracker | Home
{% endblock %}

{% block showcase %}
    <div class="container showcase">
        <h1>
            Feeding the world for cheap
        </h1>
        <div class="showcase-middleground"></div>
        <div class="showcase-background"></div>
    </div>
{% endblock showcase %}
{% block maintitle %}
<div class="main-title">
    <div class="color-cover"></div>
    <div class="title">
        <h1>
            <span class="prominent-letter">U</span>ni<span class="prominent-letter">Q</span>ue 
            <span class="prominent-letter">C</span>orn
            <!-- UniQue Corn - Issue Tracker -->
        </h1>
    </div>
</div>
{% endblock maintitle %}

{% block content %}
    <div class="main-content col-xs-12">
        <section id="features-bugs">
            <h2>
                Features & Bugs
            </h2>
        </section>
        <section class="picture-links-container">
            <div class="picture-links">
                <a href="{% url 'uqc_app' %}">
                    <div class="front-panel product-bg">
                        <span>
                            UQC <span class="longer-title">App</span>
                        </span>
                    </div>
                </a>
                <a href="{% url 'issues' %}">
                    <div class="front-panel issue-tracker-bg">
                        <span>
                            Issue Tracker
                        </span>
                    </div>
                </a>
                <a href="{% url 'blog' %}">
                    <div class="front-panel blog-bg">
                        <span>
                            Blog
                        </span>
                    </div>
                </a>
            </div>
        </section>
        <section id="events">
            <h2>
                Events
            </h2>
            <p class="general-info">All events are whole day events, starting at 9:00am till 5:00pm, unless otherwise stated.</p>
            <div class="event-item">
                <h3>UniQueCorn - Feeding People</h3>
                <div class="event-details row">
                    <p class="col-xs-12 col-sm-4"><span class="event-data">Date: </span>25th March, 2019
                    </p>
                    <p class="col-xs-12 col-sm-6"><span class="event-data">Venue: </span>The Brewery, London.
                    </p>
                </div>
                <div class="event-details row">
                    <p class="col-xs-12 col-sm-4"><span class="event-data">Date: </span>30th March, 2019
                    </p>
                    <p class="col-xs-12 col-sm-6"><span class="event-data">Venue: </span>Victoria Warehouse, Manchester.
                    </p>
                </div>
                <div class="row description">
                    <p>Our flagship product - introduction for potential customers.</p>
                </div>
            </div>
            <div  class="event-item">
                <h3>Improving UniQueCorn</h3>
                <div class="event-details row">
                    <p  class="col-xs-12 col-sm-4"><span class="event-data">Date: </span>15th April, 2019
                    </p>
                    <p  class="col-xs-12 col-sm-6"><span class="event-data">Venue: </span>Hilton Brighton Metropole, Brighton.
                    </p>
                </div>
                <div class="row description">
                        <p>As with all products, they either improve or they die. Our product is far too young to die so we choose to improve.</p>
                </div>
            </div>
            <div  class="event-item">
                <h3>UniQueCorn - A look at the future</h3>
                <div class="event-details row">
                    <p  class="col-xs-12 col-sm-4"><span class="event-data">Date: </span>5th May, 2019
                    </p>
                    <p  class="col-xs-12 col-sm-6"><span class="event-data">Venue: </span>National Railway Museum, York.
                    </p>
                </div>
                <div class="row description">
                        <p>As the railway takes you places, so we want to take our product. Join us to see what the future holds in store.</p>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

home/templates/uqc-app.html
{% extends "base.html" %}

{% block page_title %}
UniQueCorn - UQC app
{% endblock %}

{% block showcase %}
<div class="main-title">
    <div class="color-cover"></div>
    <div class="title">
        <h1>Unique Corn - UQC App</h1>
    </div>
</div>
{% endblock showcase %}

{% block content %}


<p class="uqc-app-intro">
    UniQue Corn, produces corn directly from your mobile phone. No more need to grow plants, wait for them to fruit and harvest them. Just decide the quantity you want. Hit a button and off you go. In the future we also would like to add functionality so that the corn is popped if you so wish it to be.
</p>

<p class="uqc-app-text">
    Unfortunately it is not currently available for download as we are fixing a few teething issues. For the people who have already downloaded this app, use it with caution.
</p>

<p class="uqc-app-download-info">
    Downloads will recommence soon
</p>

<p class="uqc-app-text">
    Recommending new features and reporting bugs will help us improve this app. Vote for features and bugs will increase the likelihood that these will be worked on, as well as help us fund this project.
</p>

<p class="uqc-app-text uqc-app-red">
    <span>Warning:</span><br>
There have been reports that people have died by relying solely on the corn produced by this app for their
nutrition.
</p>

{% endblock %}